# Generated by Django 5.0.1 on 2024-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='hidden_pages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='question_answer_pairs',
            field=models.TextField(blank=True),
        ),
    ]
